### ISSUE TITLE
threads_compute

### ISSUE THREAD

**Issue by OmarElfouly** [AUC-OS-Lab-S24/mmap_and_threads#5]
Same as mmap_compute but instead of taking the number of processes, it instead takes the number of threads

**Comment by Helazhary** [comment]
int *read_data(const char *filepath, int *size)
{
    FILE *file = fopen(filepath, "r");
    if (!file)
    {
        printf("Failed to open fileeeee\n");
        return NULL;
    }

    int *data = NULL;
    *size = 0;
    int number;
    char delimiter;

    while (fscanf(file, "%d%c", &number, &delimiter) != EOF)
    {
        int *temp = realloc(data, sizeof(int) * (*size + 1));
        if (!temp)
        {
            printf("Failed to allocate memory\n");
            fclose(file);
            return NULL;
        }
        data = temp;
        data[*size] = number;
        (*size)++;

        if (delimiter != ',')
        {
            break;
        }
    }

    fclose(file);
    return data;
}
